common:
  log_level: DEBUG
  index_range_path: 'data/index_range.csv'
featurize:
  data_path_raw: 'data/raw_sample/training'
  data_path_intermediate: 'data/intermediate/training'
  data_path_featurized: 'data/featurized/training'
  concept_set_members: 'data/raw_sample/concept_set_members.csv'
  test_set_pct: 0.25
  random_state: 16
train:
  model_path: 'models/'
  model_name: 'demo.json'
  random_seed: 16
infer:
  data_path: 'data/featurized/training'
  data_files:
    - 'featurized_data_train.csv'
    - 'featurized_data_test.csv'
  predictions_path: 'data/predictions/training'
  threshold: 0.5