common:
  log_level: DEBUG
  index_range_path: 'data/index_range.csv'
featurize:
  data_path_raw: 'data/raw_sample/training'
  data_path_intermediate: 'data/intermediate/training'
  data_path_featurized: 'data/featurized/training'
  concept_set_members: 'data/raw_sample/concept_set_members.csv' 
  micro_to_macro_path: 'data/raw_sample/training/microvisits_to_macrovisits.csv'
  long_covid_path: 'data/raw_sample/training/long_covid_silver_standard.csv'
  index_range_path: 'data/intermediate/training/index_range.parquet'
  utilization_path: 'data/featurized/training/utilization.parquet'
  
